// <auto-generated />
namespace CriticalWebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class perQtyPerProduct : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(perQtyPerProduct));
        
        string IMigrationMetadata.Id
        {
            get { return "201704190256240_perQtyPerProduct"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
